### ISSUE TITLE
React

### ISSUE THREAD

**Issue by vikram7** [greenfieldhq/book-club#11]
- [x] wth is it?
- [x] how does it work?
- [x] how does it compare to Ember?
- [x] when will it go 1.0?

**Comment by HeroicEric** [comment]
Done https://twitter.com/lordezar/status/708362768911572996/photo/1

We should do some more advanced ones though

**Comment by HeroicEric** [comment]
For reference, we live coded the [React Tutorial](http://facebook.github.io/react/docs/tutorial.html) as a group
